# This is a basic workflow that is manually triggered

name: Build and Deploy to GitHub Pages on Push

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #Setup nodejs and create environments.ts file
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: node server.js
        env:
          SUPABASE_DETAILS: '${{ secrets.SUPABASE_DETAILS }}'
        # Continue with build
